// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecases/userInterface.go

// Package mock_usecases is a generated GoMock package.
package mock_usecases

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entities "github.com/vishnusunil243/Job-Portal-User-service/entities"
	pb "github.com/vishnusunil243/Job-Portal-proto-files/pb"
)

// MockUsecases is a mock of Usecases interface.
type MockUsecases struct {
	ctrl     *gomock.Controller
	recorder *MockUsecasesMockRecorder
}

// MockUsecasesMockRecorder is the mock recorder for MockUsecases.
type MockUsecasesMockRecorder struct {
	mock *MockUsecases
}

// NewMockUsecases creates a new mock instance.
func NewMockUsecases(ctrl *gomock.Controller) *MockUsecases {
	mock := &MockUsecases{ctrl: ctrl}
	mock.recorder = &MockUsecasesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsecases) EXPECT() *MockUsecasesMockRecorder {
	return m.recorder
}

// GetAppliedUsersByJobId mocks base method.
func (m *MockUsecases) GetAppliedUsersByJobId(jobId string) ([]entities.Jobs, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAppliedUsersByJobId", jobId)
	ret0, _ := ret[0].([]entities.Jobs)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAppliedUsersByJobId indicates an expected call of GetAppliedUsersByJobId.
func (mr *MockUsecasesMockRecorder) GetAppliedUsersByJobId(jobId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAppliedUsersByJobId", reflect.TypeOf((*MockUsecases)(nil).GetAppliedUsersByJobId), jobId)
}

// JobApply mocks base method.
func (m *MockUsecases) JobApply(arg0 entities.Jobs, arg1 []*pb.JobSkillResponse, arg2, arg3 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "JobApply", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// JobApply indicates an expected call of JobApply.
func (mr *MockUsecasesMockRecorder) JobApply(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "JobApply", reflect.TypeOf((*MockUsecases)(nil).JobApply), arg0, arg1, arg2, arg3)
}

// UploadImage mocks base method.
func (m *MockUsecases) UploadImage(arg0 *pb.UserImageRequest, arg1 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadImage", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadImage indicates an expected call of UploadImage.
func (mr *MockUsecasesMockRecorder) UploadImage(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadImage", reflect.TypeOf((*MockUsecases)(nil).UploadImage), arg0, arg1)
}
